# Generated by Django 3.2.4 on 2024-05-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('report_path', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
